---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: order-service
      labels:
        app: order
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: order
      template:
        metadata:
          labels:
            app: order
        spec:
          containers:
            - name: order
              image: ankitakhurana25/order-service:latest
              ports:
                - containerPort: 3002