---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: aggregator-service
      labels:
        app: aggregator
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: aggregator
      template:
        metadata:
          labels:
            app: aggregator
        spec:
          containers:
            - name: aggregator
              image: ankitakhurana25/aggregator-service:latest
              ports:
                - containerPort: 3003