version: '3.4'

services:
  service1:
    image: service1:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_service1$
    volumes:
      - D:\MicroServiceRabbitMqExample\MicroServiceRabbitMqExample\Service1:/app
      - C:\Users\ankitakhurana\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_service1$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_service1$ bin/Debug/netcoreapp2.2/Service1.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

  service2:
    image: service2:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_service2$
    volumes:
      - D:\MicroServiceRabbitMqExample\MicroServiceRabbitMqExample\Service2:/app
      - C:\Users\ankitakhurana\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_service2$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_service2$ bin/Debug/netcoreapp2.2/Service2.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

